service: audit-with-lighthouse-v1

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1536
  timeout: 300
  region: eu-west-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"


 # if needed (e.g. upload snapshot)
  # iamRoleStatements:
  #  -  Effect: "Allow"
  #     Action:
  #       - "s3:PutObject"
  #     Resource: "arn:aws:s3:::<bucket name>/*"  

resources:
  Resources:
    LighthouseResultsDynamoDbTableV2:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
          - AttributeName: scantimestamp
            AttributeType: N
        KeySchema:
          - AttributeName: url
            KeyType: HASH
          - AttributeName: scantimestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  test-function:
    handler: index.handler
    environment:
      DEBUG: 0
    events:
      - http:
          path: finished-page
          method: get

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - npm run package
